pekko {
  http.server.preview.enable-http2 = on

  # JDBC-Calls blockieren den Thread im PersistenceActor, daher hier ein Dispatcher
  # Verwendung im Guardian
  actor {
    blocking-io-dispatcher {
      type = "Dispatcher"
      executor = "thread-pool-executor"
      thread-pool-executor {
        fixed-pool-size = 4
      }
      throughput = 1
    }
  }
}