pekko {
  http.server.preview.enable-http2 = on

  actor {
    serialization-bindings {
      "at.fhv.sysarch.lab2.orderprocessor.PersistenceActor$OrderPersisted" = jackson-json
    }
  }

  persistence {
    journal.plugin = "jdbc-journal"
    snapshot-store.plugin = "jdbc-snapshot-store"
  }
}

jdbc-journal {
  slick {
    profile = "slick.jdbc.H2Profile$"
    db {
      url = "jdbc:h2:mem:orders;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE;INIT=RUNSCRIPT FROM 'classpath:persistence-create-tables.sql'"
      driver = "org.h2.Driver"
      user = "sa"
      password = ""
      connectionPool = disabled
      numThreads = 1
    }
  }
}

jdbc-snapshot-store {
  slick {
    profile = "slick.jdbc.H2Profile$"
    db {
      url = "jdbc:h2:mem:orders;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE;INIT=RUNSCRIPT FROM 'classpath:persistence-create-tables.sql'"
      driver = "org.h2.Driver"
      user = "sa"
      password = ""
      connectionPool = disabled
      numThreads = 1
    }
  }
}

jdbc-read-journal {
  slick {
    profile = "slick.jdbc.H2Profile$"
    db {
      url = "jdbc:h2:mem:orders;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE;INIT=RUNSCRIPT FROM 'classpath:persistence-create-tables.sql'"
      driver = "org.h2.Driver"
      user = "sa"
      password = ""
      connectionPool = disabled
      numThreads = 1
    }
  }
}