package at.fhv.sysarch.lab2.homeautomation.shared.exceptions;

public enum ErrorCode {
    ENV_INVALID_TEMPERATURE,
    ENV_INVALID_WEATHER_CONDITION,

    MQTT_CONNECTION_FAILURE,
    MQTT_MESSAGE_PARSING_FAILURE,

    FRIDGE_INSUFFICIENT_SPACE,
    FRIDGE_INSUFFICIENT_CAPACITY,
    FRIDGE_PRODUCT_NOT_AVAILABLE,
    FRIDGE_INVALID_ORDER,
    FRIDGE_INVALID_PRODUCT,
    FRIDGE_INVALID_LINE_ITEM,

    INVALID_MODE,
    INVALID_REQUEST
}
